name: Deploy Lambdas

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your desired region
      
      - name: Install dependencies
        run: npm install 

      - name: Build Lambda packages
        run: |
          zip -r demoFunction1.zip demoFunction1
          zip -r demoFunction2.zip demoFunction2

      - name: Deploy Function 1
        run: aws lambda update-function-configuration --function-name "demoFunction1" --zip-file fileb://demoFunction1.zip 
      
      - name: Deploy Function 2
        run: aws lambda update-function-configuration --function-name "demoFunction2" --zip-file fileb://demoFunction2.zip 